### ISSUE TITLE
05.第五章-插叙:进程API 课后习题第二题

### ISSUE THREAD

**Issue by Hwangzhiyoung** [joshuap233/Operating-Systems-Three-Easy-Pieces-NOTES#1]
用fork()创建一个新进程。当它们并发（即同时）写入文件时，会发生什么？
-------
这个父子进程是可以对同一个文件描述符写入的好吧，写肯定是会写入的，但父子进程写入顺序不一定

**Comment by joshuap233** [comment]
谢谢提醒，已修改
